INSERT INTO Weather VALUES (1,'RAIN');
INSERT INTO Weather VALUES (2,'SNOW');
INSERT INTO Weather VALUES (3,'MIST');
INSERT INTO Weather VALUES (4,'CLOUDS');
INSERT INTO Weather VALUES (5,'CLEAR');

INSERT INTO Activite VALUES (1,'SKI',false, -40,5);
INSERT INTO Activite VALUES (2,'PETANQUE',true, 0,40);
INSERT INTO Activite VALUES (3,'KAYAK',false, 5,40);
INSERT INTO Activite VALUES (4,'SURF',false, 5,35);
INSERT INTO Activite VALUES (5,'EQUITATION',false, 5,40);
INSERT INTO Activite VALUES (6,'FOOTBALL',true, 0,40);
INSERT INTO Activite VALUES (7,'RUGBY',true, 0,40);
INSERT INTO Activite VALUES (8,'ESCALADE',false, 5,30);
INSERT INTO Activite VALUES (9,'TENNIS',true, 0,40);
INSERT INTO Activite VALUES (10,'PÊCHE',false, 5,40);
INSERT INTO Activite VALUES (11,'APÉRO',true, -273.15,1000);
INSERT INTO Activite VALUES (12,'BEACH VOLLEY',true, 0,40);
INSERT INTO Activite VALUES (13,'KARATÉ',true, 10,40);
INSERT INTO Activite VALUES (14,'YOGA',false, 15,35);
INSERT INTO Activite VALUES (15,'NATATION',false, 0,40);
INSERT INTO Activite VALUES (16,'GOLF',false, 0,40);
INSERT INTO Activite VALUES (17,'TIR À LARC',false, 0,40);
INSERT INTO Activite VALUES (18,'CYCLISME',false, 0,35);
INSERT INTO Activite VALUES (19,'RANDONNÉE',false, 0,35);
INSERT INTO Activite VALUES (20,'BASKET',true, 0,40);

INSERT INTO Ville VALUES (1, 'SOORTS-HOSSEGOR', null);
INSERT INTO Ville VALUES (2, 'SAINT-GREGOIRE',null);
INSERT INTO Ville VALUES (3, 'MARSEILLE',null);
INSERT INTO Ville VALUES (4, 'GRENOBLE',null);
INSERT INTO Ville VALUES (5, 'BREST',null);
INSERT INTO Ville VALUES (6, 'PARIS',null);
INSERT INTO Ville VALUES (7, 'LYON',null);
INSERT INTO Ville VALUES (8, 'DIJON',null);
INSERT INTO Ville VALUES (9, 'RENNES',null);
INSERT INTO Ville VALUES (10,'ORLEANS',null);
INSERT INTO Ville VALUES (11,'AJACCIO',null);
INSERT INTO Ville VALUES (12,'STRASBOURG',null);
INSERT INTO Ville VALUES (13,'LILLE',null);
INSERT INTO Ville VALUES (14,'ROUEN',null);
INSERT INTO Ville VALUES (15,'BORDEAUX',null);
INSERT INTO Ville VALUES (16,'TOULOUSE',null);
INSERT INTO Ville VALUES (17, 'NANTES',null);
INSERT INTO Ville VALUES (18, 'BOURG-EN-BRESSE',null);
INSERT INTO Ville VALUES (19, 'LAON',null);
INSERT INTO Ville VALUES (20, 'MOULINS',null);
INSERT INTO Ville VALUES (21, 'DIGNE-LES-BAINS',null);
INSERT INTO Ville VALUES (22, 'GAP',null);
INSERT INTO Ville VALUES (23, 'NICE',null);
INSERT INTO Ville VALUES (24, 'PRIVAS',null);
INSERT INTO Ville VALUES (25, 'CHARLEVILLE-MEZIERES',null);
INSERT INTO Ville VALUES (26, 'FOIX',null);
INSERT INTO Ville VALUES (27, 'TROYES',null);
INSERT INTO Ville VALUES (28, 'CARCASSONNE',null);
INSERT INTO Ville VALUES (29, 'RODEZ',null);
INSERT INTO Ville VALUES (30, 'CAEN',null);
INSERT INTO Ville VALUES (31, 'PERPIGNAN',null);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,20);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,20);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,20);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,20);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,20);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,19);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,19);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,19);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,19);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,19);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,18);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,18);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,18);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,18);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,18);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,17);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,17);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,17);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,17);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,17);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,16);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,16);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,16);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,16);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,16);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,15);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,15);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,15);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,15);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,15);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,14);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,14);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,14);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,14);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,14);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,13);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,13);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,13);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,13);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,13);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,12);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,12);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,12);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,12);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,12);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,11);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,11);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,11);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,11);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,11);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,10);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,10);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,10);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,10);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,10);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,9);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,9);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,9);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,9);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,9);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,8);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,8);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,8);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,8);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,8);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,7);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,7);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,7);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,7);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,7);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,6);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,6);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,6);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,6);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,6);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,5);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,5);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,5);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,5);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,5);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,4);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,4);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,4);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,4);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,4);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,3);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,3);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,3);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,3);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,3);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,2);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,2);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,2);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,2);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,2);

INSERT INTO ACTIVITE_WEATHERS VALUES (1,1);
INSERT INTO ACTIVITE_WEATHERS VALUES (2,1);
INSERT INTO ACTIVITE_WEATHERS VALUES (3,1);
INSERT INTO ACTIVITE_WEATHERS VALUES (4,1);
INSERT INTO ACTIVITE_WEATHERS VALUES (5,1);


INSERT INTO VILLE_ACTIVITES VALUES (4,1);
INSERT INTO VILLE_ACTIVITES VALUES (2,1); 
INSERT INTO VILLE_ACTIVITES VALUES (18,1); 

INSERT INTO VILLE_ACTIVITES VALUES (2,2);
INSERT INTO VILLE_ACTIVITES VALUES (6,2); 
INSERT INTO VILLE_ACTIVITES VALUES (17,2); 

INSERT INTO VILLE_ACTIVITES VALUES (11,3); 
INSERT INTO VILLE_ACTIVITES VALUES (12,3); 
INSERT INTO VILLE_ACTIVITES VALUES (2,3); 

INSERT INTO VILLE_ACTIVITES VALUES (1,4); 
INSERT INTO VILLE_ACTIVITES VALUES (8,4);
INSERT INTO VILLE_ACTIVITES VALUES (19,4);

INSERT INTO VILLE_ACTIVITES VALUES (4,5); 
INSERT INTO VILLE_ACTIVITES VALUES (13,5); 
INSERT INTO VILLE_ACTIVITES VALUES (14,5); 

INSERT INTO VILLE_ACTIVITES VALUES (20,6); 
INSERT INTO VILLE_ACTIVITES VALUES (2,6);
INSERT INTO VILLE_ACTIVITES VALUES (6,6); 

INSERT INTO VILLE_ACTIVITES VALUES (10,7); 
INSERT INTO VILLE_ACTIVITES VALUES (14,7); 
INSERT INTO VILLE_ACTIVITES VALUES (15,7); 

INSERT INTO VILLE_ACTIVITES VALUES (7,8);
INSERT INTO VILLE_ACTIVITES VALUES (20,8);
INSERT INTO VILLE_ACTIVITES VALUES (16,8);

INSERT INTO VILLE_ACTIVITES VALUES (10,9); 
INSERT INTO VILLE_ACTIVITES VALUES (20,9); 
INSERT INTO VILLE_ACTIVITES VALUES (16,9); 

INSERT INTO VILLE_ACTIVITES VALUES (2,10); 
INSERT INTO VILLE_ACTIVITES VALUES (3,10); 
INSERT INTO VILLE_ACTIVITES VALUES (4,10); 

INSERT INTO VILLE_ACTIVITES VALUES (5,11); 
INSERT INTO VILLE_ACTIVITES VALUES (20,11); 
INSERT INTO VILLE_ACTIVITES VALUES (17,11); 

INSERT INTO VILLE_ACTIVITES VALUES (14,12); 
INSERT INTO VILLE_ACTIVITES VALUES (2,12); 
INSERT INTO VILLE_ACTIVITES VALUES (13,12); 

INSERT INTO VILLE_ACTIVITES VALUES (18,13);
INSERT INTO VILLE_ACTIVITES VALUES (9,13); 
INSERT INTO VILLE_ACTIVITES VALUES (3,13); 

INSERT INTO VILLE_ACTIVITES VALUES (7,14); 
INSERT INTO VILLE_ACTIVITES VALUES (6,14); 
INSERT INTO VILLE_ACTIVITES VALUES (5,14); 

INSERT INTO VILLE_ACTIVITES VALUES (7,15); 
INSERT INTO VILLE_ACTIVITES VALUES (6,15); 
INSERT INTO VILLE_ACTIVITES VALUES (5,15); 

INSERT INTO VILLE_ACTIVITES VALUES (8,16); 
INSERT INTO VILLE_ACTIVITES VALUES (10,16); 
INSERT INTO VILLE_ACTIVITES VALUES (4,16); 

INSERT INTO VILLE_ACTIVITES VALUES (16,17); 
INSERT INTO VILLE_ACTIVITES VALUES (13,17); 
INSERT INTO VILLE_ACTIVITES VALUES (10,17); 

INSERT INTO VILLE_ACTIVITES VALUES (4,18); 
INSERT INTO VILLE_ACTIVITES VALUES (9,18); 
INSERT INTO VILLE_ACTIVITES VALUES (18,18); 

INSERT INTO VILLE_ACTIVITES VALUES (7,19); 
INSERT INTO VILLE_ACTIVITES VALUES (2,19); 
INSERT INTO VILLE_ACTIVITES VALUES (14,19); 

INSERT INTO VILLE_ACTIVITES VALUES (7,20); 
INSERT INTO VILLE_ACTIVITES VALUES (6,20); 
INSERT INTO VILLE_ACTIVITES VALUES (15,20); 

INSERT INTO VILLE_ACTIVITES VALUES (11,21); 
INSERT INTO VILLE_ACTIVITES VALUES (12,21); 
INSERT INTO VILLE_ACTIVITES VALUES (4,21); 

INSERT INTO VILLE_ACTIVITES VALUES (9,22); 
INSERT INTO VILLE_ACTIVITES VALUES (4,22); 
INSERT INTO VILLE_ACTIVITES VALUES (2,22); 

INSERT INTO VILLE_ACTIVITES VALUES (17,23); 
INSERT INTO VILLE_ACTIVITES VALUES (16,23); 
INSERT INTO VILLE_ACTIVITES VALUES (13,23); 

INSERT INTO VILLE_ACTIVITES VALUES (4,24); 
INSERT INTO VILLE_ACTIVITES VALUES (19,24); 
INSERT INTO VILLE_ACTIVITES VALUES (7,24);

INSERT INTO VILLE_ACTIVITES VALUES (11,25); 
INSERT INTO VILLE_ACTIVITES VALUES (10,25); 
INSERT INTO VILLE_ACTIVITES VALUES (9,25);

INSERT INTO VILLE_ACTIVITES VALUES (5,26); 
INSERT INTO VILLE_ACTIVITES VALUES (9,26); 
INSERT INTO VILLE_ACTIVITES VALUES (6,26);

INSERT INTO VILLE_ACTIVITES VALUES (2,27); 
INSERT INTO VILLE_ACTIVITES VALUES (9,27); 
INSERT INTO VILLE_ACTIVITES VALUES (8,27);

INSERT INTO VILLE_ACTIVITES VALUES (15,28); 
INSERT INTO VILLE_ACTIVITES VALUES (7,28); 
INSERT INTO VILLE_ACTIVITES VALUES (17,28); 

INSERT INTO VILLE_ACTIVITES VALUES (17,29); 
INSERT INTO VILLE_ACTIVITES VALUES (13,29); 
INSERT INTO VILLE_ACTIVITES VALUES (3,29); 

INSERT INTO VILLE_ACTIVITES VALUES (20,30); 
INSERT INTO VILLE_ACTIVITES VALUES (9,30); 
INSERT INTO VILLE_ACTIVITES VALUES (10,30); 

INSERT INTO VILLE_ACTIVITES VALUES (11,31); 
INSERT INTO VILLE_ACTIVITES VALUES (8,31); 
INSERT INTO VILLE_ACTIVITES VALUES (18,31); 




